- ros_topic_name: "/clock" ## what you want to match the gazebo topic to ros2 topic
  gz_topic_name: "/clock" ## From Gazebo topic
  ros_type_name: "rosgraph_msgs/msg/Clock" ##ROS type
  gz_type_name: "gz.msgs.Clock" ## Gazebo Trasnport type
  direction: GZ_TO_ROS ## ROS_TO_GZ BIDRECTIONAL

- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/empty/model/food_del_robot/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/model/food_del_robot/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/model/food_del_robot/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ